export default function handler(req, res) {
    let sentences = [
        "The cat sits on the mat.",
        "She sells seashells by the seashore.",
        "A big dog barks loudly.",
        "I love to play in the sun.",
        "The sky is bright and blue.",
        "The moon shines at night.",
        "The grass feels soft under my feet.",
        "I see a bird in the tree.",
        "He runs fast in the race.",
        "The dog barks at the stranger.",
        "It is a warm and sunny day.",
        "I like to jump on the trampoline.",
        "The ball is red and bouncy.",
        "I have a book about dinosaurs.",
        "The flowers are colorful and pretty.",
        "The car drives down the road.",
        "I am happy to see my friends.",
        "I see a tall tree in the park.",
        "It is raining outside today.",
        "The bird sings a sweet song.",
        "The fish swims in the clear water.",
        "The dog sleeps on the soft bed.",
        "The tree has green leaves.",
        "I have a shiny red ball.",
        "The sun is shining brightly.",
        "She is reading a funny book.",
        "He is running in the field.",
        "The apple is red and juicy.",
        "I see the stars in the sky.",
        "The sky is clear and blue.",
        "The grass is wet from the rain.",
        "I love my playful dog.",
        "I see a butterfly in the garden.",
        "The flowers are blooming in spring.",
        "I like to eat cold ice cream.",
        "The rain falls softly on the roof.",
        "I like to play outside with my friends.",
        "The bird flies high in the sky.",
        "The car zooms down the street.",
        "She is my best friend at school.",
        "I see a rainbow after the rain.",
        "The tree is full of green leaves.",
        "The sun feels hot on my skin.",
        "I am learning new things every day.",
        "The dog is friendly and wagging its tail.",
        "I see a fluffy cloud in the sky.",
        "The stars twinkle at night.",
        "The fish swims in the small pond.",
        "The chair is big and comfortable.",
        "The book is old but interesting.",
        "The ball is round and bouncy.",
        "It is a cool and breezy day.",
        "The snow falls softly on the ground.",
        "I like to jump rope with my friends.",
        "I am drinking cold water.",
        "She is jumping high on the trampoline.",
        "I see a squirrel in the park.",
        "The car is blue and shiny.",
        "The bike is fast and fun to ride.",
        "The cat is sleepy and curled up.",
        "I like to draw pictures of animals.",
        "The puppy is cute and playful.",
        "The tree is tall and strong.",
        "The bird sings a beautiful song.",
        "I am walking in the park with my dog.",
        "She is eating a tasty sandwich.",
        "The frog hops on the lily pad.",
        "The bear is big and furry.",
        "I see a ladybug on the flower.",
        "The water is clear and cool.",
        "The moon is full and bright.",
        "The dog is wagging its tail happily.",
        "I see a pretty flower in the garden.",
        "The cookie is sweet and delicious.",
        "I like to read books before bed.",
        "I hear the rain tapping on the window.",
        "The lion roars loudly in the jungle.",
        "The fish jumps out of the water.",
        "The clouds are fluffy and white.",
        "The dog loves to run in the park.",
        "The moon is shining in the night sky.",
        "The ice is cold and slippery.",
        "I like to swim in the pool.",
        "The fire is warm and cozy.",
        "The sky is dark during the night.",
        "The tiger is strong and fast.",
        "The bird has colorful feathers.",
        "The bear lives in the forest.",
        "The rabbit hops quickly in the field.",
        "The snow is cold and white.",
        "The monkey swings from tree to tree.",
        "The cat plays with a ball of yarn.",
        "The frog jumps high into the air.",
        "I like playing soccer with my team.",
        "The apple is juicy and sweet.",
        "I see a dog playing in the park.",
        "The rabbit eats fresh carrots.",
        "The sun is setting in the evening.",
        "I hear the birds chirping in the trees.",
        "The dog likes to chew on bones.",
        "The cat loves to eat fish.",
        "I see a snake slithering on the ground.",
        "The cake is delicious and moist.",
        "The squirrel climbs up the tall tree.",
        "I am playing with my favorite toys.",
        "The bird flies high above the clouds.",
        "The bear eats honey from the hive.",
        "The monkey climbs the tree quickly.",
        "The dog likes to play fetch with a ball.",
        "The ball is bouncing on the ground.",
        "I see a rainbow in the sky after the rain.",
        "The car is parked in the driveway.",
        "I like to ride my bike in the park.",
        "The kitten is small and fluffy.",
        "The bird is flying in the clear sky.",
        "I like to jump high on the trampoline.",
        "The apple is green and crunchy.",
        "I see a ladybug sitting on a leaf.",
        "The frog is jumping into the pond.",
        "I like to play games with my friends.",
        "The flowers smell sweet and fresh.",
        "The stars twinkle in the dark sky.",
        "I am wearing my new shoes.",
        "I like to play with my dog in the yard.",
        "The moon is bright and beautiful at night.",
        "The fish swims in the clear pond.",
        "The dog is barking loudly at the door.",
        "The chair is soft and comfortable.",
        "I have a pet cat named Whiskers.",
        "The bunny hops around the garden.",
        "I love to eat chocolate ice cream.",
        "The ice cream is cold and creamy.",
        "The shoes are new and shiny.",
        "The dog runs fast in the field.",
        "I see a red balloon floating in the air.",
        "The water is warm in the pool.",
        "I see a big tree in the forest.",
        "The kitten is playing with a toy.",
        "The lion is strong and brave.",
        "The horse is running in the meadow.",
        "The cow gives fresh milk every morning.",
        "I like to play on the sandy beach.",
        "I see a fish swimming in the pond.",
        "The bird is chirping in the tree.",
        "I hear a car horn honking loudly.",
        "The tree has many green leaves.",
        "I see the stars shining at night.",
        "The cat is scratching the scratching post.",
        "I see the sun rise in the morning.",
        "The monkey is playful and funny.",
        "I hear the wind blowing through the trees.",
        "The duck swims in the small pond.",
        "I like to color pictures with crayons.",
        "The bunny eats fresh green grass.",
        "The fish is swimming in the clear water.",
        "The giraffe has a very long neck.",
        "I like to play in the sand at the beach.",
        "I see a butterfly flying in the garden.",
        "The pig is rolling in the muddy puddle.",
        "The turtle walks slowly on the ground.",
        "The deer runs fast through the forest.",
        "The owl hoots loudly at night.",
        "I see the moon glowing in the sky.",
        "The dog loves to fetch the ball.",
        "I like to play with my friends at school.",
        "The pumpkin is orange and round.",
        "The tree has many ripe apples.",
        "I see a rainbow after the rain stops.",
        "The frog croaks loudly in the pond.",
        "I like to play hide and seek with my friends.",
        "The chicken lays eggs in the coop.",
        "The dog loves to run in the big yard.",
        "I like to ride horses in the field.",
        "The bird is sitting in the tall tree.",
        "The cat chases the mouse around the house.",
        "The lion roars loudly in the jungle.",
        "The elephant has big ears and a long trunk.",
        "I see the sun shining in the sky.",
        "The dog is barking at the mailman.",
        "I like to eat pizza with my family.",
        "I see the stars twinkling in the night sky.",
        "The fish is swimming in the fish tank.",
        "The dog is sleeping on its cozy bed.",
        "The bird flies gracefully in the air.",
        "I like to play with my toys in my room.",
        "The flowers bloom beautifully in the garden.",
        "I see a big cloud floating in the sky.",
        "The kitten is purring softly on my lap.",
        "The owl stays awake during the night.",
        "The cow gives milk every morning.",
        "I like to jump on the trampoline with my friends.",
        "The squirrel runs up the tree quickly.",
        "The cat climbs the tree to catch a bird.",
        "I hear the sound of rain on the roof.",
        "I see a rainbow after the rain stops.",
        "The bird is perched on the wooden fence.",
        "The dog loves to play fetch with a stick.",
        "I like to play soccer with my friends.",
        "The cat is sleeping in the warm sun.",
        "I like to read books in my cozy bed.",
        "I hear the wind blowing through the tall trees.",
        "The fish swims happily in the clear pond.",
        "The dog likes to play in the big park.",
        "I see a cloud shaped like a rabbit.",
        "The rabbit hops around the green yard.",
        "The bird sings a cheerful song in the morning.",
        "I see the stars shining brightly at night.",
        "The dog loves to go for walks in the park.",
        "The frog jumps onto the green lily pad.",
        "I see a butterfly flying in the colorful garden.",
        "The cat is licking its soft paw.",
        "The bird is flying high in the blue sky.",
        "I see the moon rising in the evening.",
        "The dog is wagging its tail happily.",
        "I hear the sound of waves on the beach.",
        "The lion is sleeping under the shady tree.",
        "I see a fish swimming in the clear water.",
        "The cat is chasing a small mouse.",
        "The bird is sitting in its cozy nest.",
        "I see a rainbow in the sky after the rain.",
        "The dog likes to run fast in the park.",
        "I see a turtle swimming in the pond.",
        "The butterfly is flying around the flowers.",
        "The cat is meowing loudly for food.",
        "I see a squirrel climbing up the tall tree."
    ];

    function getRandomSentences(arr, num) {
        let shuffled = arr.sort(() => 0.5 - Math.random());
        return shuffled.slice(0, num);
    }

    res.status(200).json({
        sentences: getRandomSentences(sentences, 2),
    });
};